# Generated by Django 5.2.7 on 2025-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='annotation',
            field=models.TextField(blank=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата издания'),
        ),
    ]
