# Generated by Django 5.2.7 on 2025-11-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_annotation_book_publication_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
