# Generated by Django 5.2.7 on 2025-11-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_author_options_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка на книгу'),
        ),
    ]
