# Generated by Django 5.2.7 on 2025-11-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_author_options_alter_book_options_book_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_link',
            field=models.URLField(blank=True, help_text='Откроется при клике на изображение обложки', verbose_name='Ссылка при клике на обложку'),
        ),
        migrations.AddField(
            model_name='book',
            name='detail_link',
            field=models.URLField(blank=True, help_text='Будет использована в кнопке на детальной странице', verbose_name='Ссылка для кнопки «Перейти к книге»'),
        ),
    ]
