# Generated by Django 5.2.7 on 2025-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_book_link_book_cover_link_book_detail_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Жанр')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.URLField(blank=True, verbose_name='Ссылка при клике на обложку'),
        ),
        migrations.AlterField(
            model_name='book',
            name='detail_link',
            field=models.URLField(blank=True, verbose_name='Ссылка для кнопки'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='main.genre', verbose_name='Жанры'),
        ),
    ]
