# Generated by Django 5.2.7 on 2025-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_genre_alter_book_cover_alter_book_cover_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_link',
            field=models.URLField(blank=True, help_text='Откроется при клике на изображение обложки', verbose_name='Ссылка при клике на обложку'),
        ),
        migrations.AlterField(
            model_name='book',
            name='detail_link',
            field=models.URLField(blank=True, help_text='Будет использована в кнопке на детальной странице', verbose_name='Ссылка для кнопки «Перейти к книге»'),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
